<^>!q::SendRaw, !
<^>!w::SendRaw, "
<^>!e::SendRaw, #
<^>!r::SendRaw, ¤
<^>!t::SendRaw, `%
<^>!y::SendRaw, &
<^>!u::SendRaw, /
<^>!i::SendRaw, (
<^>!o::SendRaw, )
<^>!p::SendRaw, =
<^>!å::SendRaw, ?
<^>!a::SendRaw, '
<^>!s::SendRaw, @
<^>!d::SendRaw, £
<^>!f::SendRaw, $
<^>!g::SendRaw, ^
<^>!h::SendRaw, &
<^>!j::SendRaw, {
<^>!k::SendRaw, [
<^>!l::SendRaw, ]
<^>!ö::SendRaw, }
<^>!ä::SendRaw, \
<^>!z::SendRaw, +
<^>!x::SendRaw, -
<^>!c::SendRaw, *
<^>!v::SendRaw, /
<^>!b::SendRaw, ~
